### ISSUE TITLE
Unknown data type -1

### ISSUE THREAD

**Issue by ghost** [mikeobrien/TDMSReader#8] opened 2016-01-16 13:29 UTC
Hello,

When I try to open tdms files, the reader throws an exception "Unknown data type -1".
That occurs in the Open() operation:

```
var tdms = new NationalInstruments.Tdms.File(filePath);
tdms.Open();
```

This exceptions only occurs sometimes, but I would like to know why. Maybe a problem in the files or maybe a problem with the reader with newest versions of the files.

Thanks in advance!

**Comment by mikeobrien** [comment] 2016-01-21 13:53
I'm not really sure what could be causing the problem, haven't seen that before. Might want to grab the code and debug it while opening your file, will probably help troubleshoot.

**Comment by tommyja** [comment] 2016-03-19 19:52
@rafa0809 if you post a file with the issue I will take a look.

**Comment by bhw7** [comment] 2017-05-31 19:55
Ran into this issue as well. Have two example files for you @tommyja 

[https://github.com/NIVeriStandAdd-Ons/Time-Align-NIVS-TDMS-Files-Tool/blob/master/Example%20Files/100k%208133.tdms](url)

[https://github.com/NIVeriStandAdd-Ons/Time-Align-NIVS-TDMS-Files-Tool/blob/master/Example%20Files/100k%208108.tdms](url)

**Comment by bhw7** [comment] 2017-05-31 20:12
Line 66 of the Reader.cs file gave -1 which is the source of this issue.

**Comment by mikeobrien** [comment] 2017-06-13 14:12
Thx! I'll try to take a look as soon as I can. Sorry for the delayed response.

**Comment by tom-mcs** [comment] 2019-02-12 00:08
I am also having this issue. Is there any insight into what is happening? 

Stepping through: 
File.cs `Open()` is calling `LoadMetadata(reader).ToList();`
DataType.cs `GetClrType(int dataType)` is throwing the exception.

From the stack:
Reader.cs `ReadMetadata(Segment segment)` is calling `GetClrType(metadata.RawData.DataType)`

This means that `metadata.RawData.DataType` is being set to -1 in the line before (i.e. Reader.cs line 66) 
`metadata.RawData.DataType = _reader.ReadInt32();`
It should be set (in my case) to 10: DoubleFloat

**Comment by tom-mcs** [comment] 2019-02-12 01:49
Interesting clue:
The call to `_reader.ReadInt32()` immediately prior to the one returning -1. Assigns a value of 4713 to `rawDataIndexLength`. 

4713, according to [the tdms whitepaper](http://www.ni.com/white-paper/5696/en/) refers to the _version number_ of the tdms file format, which wouldn't seem to have much to do with the rawDataIndexLength. I have observed this result with two separate .tdms files.

Perhaps something is being read out of order for some cases of tdms files.

**Comment by tom-mcs** [comment] 2019-02-12 02:08
Oh solved. 

4713 refers to TDMS2.0. As discussed in another issue, this project only supports TDMS1.0. Is that correct? I may be able to use 1.0 in my project.

**Comment by dylanmeysmans** [comment] 2020-01-17 11:12
@ghost @tom-mcs @betsalel-williamson The unrecognized data type -1 (= 0xFFFFFFFF) is DAQmx raw data, which TDMSReader does not currently support. I am closing this issue as a duplicate of #18, which has more information on the subject.

**Closed by dylanmeysmans** 2020-01-17 11:12 UTC
Labels: duplicate
